# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

`Types-UUID`
	:runtime-requirement    [ :on "perl 5.008"^^:CpanId ];
	:runtime-requirement    [ :on "Type::Tiny 1.000000"^^:CpanId ];
	:runtime-requirement    [ :on "UUID::Tiny 1.02"^^:CpanId ];
	:test-requirement       [ :on "Test::More 0.96"^^:CpanId ];
	:test-requirement       [ :on "Test::TypeTiny"^^:CpanId ];
	:test-recommendation    [ :on "URI"^^:CpanId ];
	.

